player-ui/player

.autorc, .circleci/config.yml, WORKSPACE, package.json, scripts/delete-old-prerelease.js, scripts/release.sh, tools/cli/BUILD, yarn.lock
Fixes #1 
Adding build integration to publish all js packages to `npm`
=> NPM publishing support

.bazelrc, WORKSPACE, core/player/src/player.ts, docs/site/BUILD, react/player/src/player.tsx, scripts/release.sh, scripts/workspace-status.sh
- Fixes the stamping for version and sha in `core` and `web` modules
- Stamps the nextjs docs for analytics id
=> Fix version stamping. Add stamping to nextjs docs

core/view/src/resolver/types.ts
The namespace only conflicts when using the compiled output (which uses the `Validation` name to the local interface)
=> Fix validation namespace collision in compiled module

.circleci/config.yml
only really need to persist the `.ios-build-number`, not sure if this is why the release stage cant attach the workspace, but maybe
=> dont persist everything, just the ios-build-number

.circleci/config.yml, android/build.bzl, android/demo/src/androidTest/java/com/intuit/player/android/reference/demo/test/base/ApplitoolsTest.kt
=> read sha as batch id

.autorc
CocoaPods doesn't allow it
Maven also shouldn't have it
NPM seems to strip it internally
=> remove version prefix

.circleci/config.yml
the `upload-assets` plugin for auto apparently does not care if the file does not exist
=> persist iOS zip from iOS part of build

WORKSPACE, android/demo/BUILD, android/player/src/main/java/com/intuit/player/android/lifecycle/PlayerViewModel.kt, jvm/core/src/main/kotlin/com/intuit/player/jvm/core/player/state/PlayerFlowState.kt, jvm/core/src/test/kotlin/com/intuit/player/jvm/core/player/HeadlessPlayerTest.kt, jvm/core/src/test/kotlin/com/intuit/player/jvm/core/player/state/ErrorStateTest.kt
=> enhance error state deserialization & stacktrace logging in player view model

BUILD.bazel, WORKSPACE, docs/BUILD, docs/site/BUILD, docs/site/components/Navigation.tsx, docs/site/components/Search.tsx, docs/site/config/constants.ts, docs/site/next.config.mjs, generated.bzl, package.json, scripts/release.sh, scripts/workspace-status.sh, xcode/Podfile.lock
Fixes: #47
Re-organizes how the docs site is merged together. Now creates a `.tar.gz` of the full merged site, stamps that result to a new `.tar.gz`, and uploads that to github-pages. 
The merged `.tar.gz` is stamped twice depending on it's output directory (`/latest`, `/next`, `/<version>`)
Adds a menu selection for `latest`, `next` and any released version
=> Add subpath support for published docs

core/view/src/__tests__/view.test.ts, core/view/src/parser/index.ts
Story 8385, if switch node is empty, remove the node
=> switch removal from empty node

ios/packages/reference-assets/UITests/ActionAssetUITests.swift, ios/packages/reference-assets/UITests/BaseTestCase.swift, ios/packages/reference-assets/UITests/CollectionAssetUITests.swift, ios/packages/reference-assets/UITests/InfoAssetUITests.swift, ios/packages/reference-assets/UITests/InputAssetUITests.swift, ios/packages/reference-assets/UITests/TextAssetUITests.swift
tweak how applitools screenshots are done so they all have an implicit wait time to allow for the UI to complete animations
=> add delay before screenshotting for animations to finish

ios/packages/core/Sources/Player/HeadlessPlayer.swift, ios/packages/core/Tests/HeadlessPlayerTests.swift
Primarily to enable plugins to register other plugins that have a JS resource
=> [iOS] add registerPlugin(_:) to HeadlessPlayer API

jvm/j2v8/build.bzl, jvm/j2v8/libs/BUILD
=> change platform groupid

ios/packages/core/Sources/Types/Assets/BaseAssetRegistry.swift, ios/packages/core/Sources/Types/Beacon.swift, ios/plugins/BaseBeaconPlugin/Sources/BaseBeaconPlugin.swift, ios/plugins/ExternalActionPlugin/Tests/ExternalActionPluginTests.swift
- Adds public initializer to Beacon related structs that is necessary for some custom beacon usage
- Make properties on BaseBeaconPlugin public for implementing BeaconPlugin for non-SwiftUI usage
- Makes some registry types/members public for custom registry implementations, such as for a headless test player
=> [iOS] make some additional properties public

ios/packages/swiftui/Sources/SwiftUIPlayer.swift
Xcode14 displays runtime warnings for some published variables when they are updated 
This was not reproducible with the reference assets but with an integration that sets up several values in EnvironmentValues
=> [iOS] fix runtime warnings for published variables in Xcode14

ios/packages/core/Sources/Types/Beacon.swift, ios/packages/reference-assets/Sources/SwiftUI/ActionAsset.swift, ios/plugins/BeaconPlugin/Sources/SwiftUIBeaconPlugin.swift, ios/plugins/BeaconPlugin/ViewInspector/BeaconPluginTests.swift
Sending `metaData.beacon` required decoding a specific type before, but the requirement is relaxed now to fit a protocol, and is mapped internally to a encodable structure that matches what the beacon plugin expects
=> [iOS] relax requirements for sending beacon metadata

.circleci/config.yml
=> run a separate workflow for forked PRs without write capable cache keys

ios/packages/core/Sources/Types/Assets/BaseAssetRegistry.swift, ios/packages/swiftui/Sources/SwiftUIPlayer.swift, ios/packages/swiftui/Tests/SwiftUIRegistryTests.swift, ios/plugins/ExternalActionViewModifierPlugin/ViewInspector/ExternalActionViewModifierPluginTests.swift
When holding SwiftUIPlayer context outside of `ManagedPlayer`, it also holds the asset registry. Upon each invocation of `apply` the plugins would reregister all their assets, burning cycles in JSCore. This adds an equality check to no-op that exact duplicate registrations, rather than just checking for overriding
=> [iOS] SwiftUIRegistry perf fix

scripts/after-shipit-pod-push.js
Should address failure in https://app.circleci.com/pipelines/github/player-ui/player/860/workflows/37561963-1699-4d1e-a3aa-673f595cabfe/jobs/3732
For regular/prereleases the release name is the same as the tag, but not for canary, so we should compare against the tag name
=> compare against tag name instead of release name

index.bzl
Restores the `bundle` property in `package.json` for packages that have webpack bundles, so they can be copied easily into resource bundles for iOS
=> add bundle property to package for targets that produce webpack bundles

.circleci/config.yml, index.bzl, xcode/Podfile
Adds the built bundles into `js_library_data` so bundles will be included in the published `dist`
=> add webpack bundles to js_library_data

ios/packages/swiftui/Sources/ManagedPlayer/ManagedPlayer.swift
JSVirtualMachine cleans up memory better by itself this way, and lets us full teardown between flows
=> Update default context for ManagedPlayer to use JSVirtualMachine

scripts/after-shipit-pod-push.js
Added a flag to track if the canary hook is called, rather than spend time polling when we know there will be no tag/release
<details>
<summary>📦 Published PR as canary version: <code>0.3.1--canary.123.4401</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.3.1--canary.123.4401
</details>
=> dont try to push pod if its a canary release

scripts/release.sh
Rationale: Even if docs fail to upload, the artifacts are more important since we can more easily fix docs upload manually.
<details>
<summary>📦 Published PR as canary version: <code>0.4.0--canary.129.4506</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.4.0--canary.129.4506
</details>
=> Publish to Maven Central before the docs

core/player/src/expressions/__tests__/parser.test.ts, core/player/src/expressions/__tests__/utils.test.ts, core/player/src/expressions/evaluator.ts, core/player/src/expressions/index.ts, core/player/src/expressions/parser.ts, core/player/src/expressions/types.ts
- Expose `parseExpression` from the expression parser
- Adds a `strict` flag to `parseExpression` that will (when disabled) attach any parsing errors to the top-level node instead of throwing
=> Expose utils for expression LSP

core/player/src/view/parser/__tests__/parser.test.ts, core/player/src/view/parser/index.ts
If an Asset has a property that is keyed by a Symbol, that property is not retained in the final view output. While this can't really happen with content loaded from a JSON file, for content that is dynamically generated there may be symbols present.
=> Parse and Forward Symbols in the View Parser

scripts/release.sh
<details>
<summary>📦 Published PR as canary version: <code>0.3.1--canary.134.4642</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.3.1--canary.134.4642
</details>
=> Increase Maven Central timeouts to 10 min

core/make-flow/src/index.ts, core/player/src/__tests__/validation.test.ts, core/player/src/controllers/data.ts, core/player/src/player.ts, core/player/src/plugins/default-exp-plugin.ts, core/player/src/schema/__tests__/schema.test.ts, core/player/src/schema/schema.ts, core/player/src/string-resolver/index.ts, core/player/src/validator/validation-middleware.ts, core/types/src/index.ts, plugins/auto-scroll/react/src/__tests__/plugin.test.tsx, plugins/auto-scroll/react/src/plugin.tsx, plugins/data-change-listener/core/BUILD, plugins/data-change-listener/core/src/index.test.ts, plugins/data-change-listener/core/src/index.ts
Sync latest code
Sync latest code
<details>
<summary>📦 Published PR as canary version: <code>0.4.0--canary.131.4657</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.4.0--canary.131.4657
</details>
=> sync up to latest

ios/packages/swiftui/Sources/ManagedPlayer/ManagedPlayer.swift
The changes to use JSVirtualMachine by default changed to unload player when it disappeared. Some presentation contexts over ManagedPlayer would trigger onDisappear unintentionally unloading player.
Switch to explicitly unload context on state changes for ManagedPlayer, rather than when SwiftUI disappears
=> [iOS] ManagedPlayer only unload context on state changes, not when player disappears

ios/packages/swiftui/Sources/ManagedPlayer/ManagedPlayer.swift, ios/packages/swiftui/Sources/ManagedPlayer/ScrollPlugin.swift, ios/packages/swiftui/ViewInspector/ManagedPlayer/ManagedPlayerTests.swift
makes `ScrollPlugin` public to expose `\.scrollToProxy` and `\.playerScrollPluginSize` for consistent usage in and out of ManagedPlayer for scrolling
=> make ScrollPlugin public to be used outside ManagedPlayer

WORKSPACE
trying to fix `tart` 404 in CI that i cant reproduce locally, guessing based on the stack trace
=> Update rules_player version to fix iOS build

ios/packages/demo/Sources/MockFlows.swift, ios/packages/reference-assets/Sources/SwiftUI/InfoAsset.swift, ios/packages/reference-assets/Sources/SwiftUI/InputAsset.swift, plugins/reference-assets/mocks/input/input-basic.json
Fixes #167 
Added a note to the iOS input asset to match web.
Changed the styling of the label on the iOS input asset to more closely match web.
Added padding underneath the info asset to match web (was affecting input transition mock flow)
=> Added note to input asset

ios/packages/demo/Sources/MockFlows.swift, ios/packages/reference-assets/Sources/SwiftUI/InfoAsset.swift, ios/packages/reference-assets/ViewInspector/SwiftUI/InfoAssetTests.swift, plugins/reference-assets/mocks/info/info-footer.json
resolves #162 
Added optional footer asset to bottom of info reference asset, for the SwiftUI reference asset
Demo mock:
=> [Issue 162] iOS: Add footer to info reference asset

plugins/auto-scroll/react/src/__tests__/plugin.test.tsx, plugins/reference-assets/core/src/assets/info/__tests__/transform.test.ts, plugins/reference-assets/core/src/assets/info/index.ts, plugins/reference-assets/core/src/assets/info/transform.ts, plugins/reference-assets/core/src/assets/info/types.ts, plugins/reference-assets/core/src/plugin.ts, plugins/reference-assets/mocks/info/info-basic.json, plugins/reference-assets/react/src/assets/info/Info.tsx
This PR adds a transform for the Info asset. The transform adds a property called segmentedAssets to the asset. SegmentedAssets is a collection of next and prev actions and extracting the logic out of the react component makes it useable for ios and android. 
Further support would be required by android and ios to use segmentedAssets
=> Core: add Support For Segmented Assets

ios/packages/swiftui/Tests/ManagedPlayer/ManagedPlayerViewModelTests.swift
To hopefully address #12, Xcode15 was warning that `wait` for expecations in async context will be an error in swift 6 (not out yet), hoping that just means pre swift-6 they didnt document that it wasnt supported, and swapping will fix the flakiness
after several back to back runs, no random failures
resolves #12 
=> apply swift 6 warning fix to flaky iOS tests

ios/packages/swiftui/Tests/ManagedPlayer/ManagedPlayerViewModelTests.swift
Pretty sure i tried this before, but it seems to work now?
=> store cancellables in ManagedPlayerViewModelTests

.circleci/config.yml
=> Singular workflow for CI

ios/plugins/BaseBeaconPlugin/Sources/BaseBeaconPlugin.swift, ios/plugins/BeaconPlugin/Sources/SwiftUIBeaconPlugin.swift, ios/plugins/ExpressionPlugin/Sources/ExpressionPlugin.swift, ios/plugins/ExternalActionPlugin/Sources/ExternalActionPlugin.swift, ios/plugins/ExternalActionViewModifierPlugin/Sources/ExternalActionViewModifierPlugin.swift, ios/plugins/MetricsPlugin/Sources/MetricsPlugin.swift, ios/plugins/SwiftUICheckPathPlugin/Sources/SwiftUICheckPathPlugin.swift, scripts/after-shipit-pod-push.js
Remove strong references to `self` in plugin closures
<details>
<summary>📦 Published PR as canary version: <code>0.3.1--canary.209.6539</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.3.1--canary.209.6539
</details>
=> iOS: remove strong self references in plugins

BUILD.bazel, scripts/after-shipit-pod-push.js
- Fixed missing resource bundle for `StageDataRevertPlugin` in the pod zip
- fixed stdout for `after-shipit-pod-push` when using `execSync` so the pod errors will show in the build log
=> fix iOS release, and fix script to show output properly

core/player/src/__tests__/data.test.ts, core/player/src/controllers/data/controller.ts, core/player/src/controllers/data/index.ts, core/player/src/controllers/data/utils.ts, core/player/src/controllers/index.ts, core/player/src/controllers/view/controller.ts, core/player/src/player.ts, core/player/src/types.ts
Currently, after Player reaches an end state it returns a serialized version of the final data model. One potential issue that may arise is if a binding needs to be evaluated to retrieve a value in the data model. One potential use case for this would be easily using a stored value to access another stored value. 
This solution uses a class that also extends `DataModelWithParser` but wraps a `DataController` instance. This allows a similar API while preventing any `set` or `delete` calls from being executed against the model while still allowing retrievals though the `get` method.  To make this easy to use, a new method `makeReadOnly()` has been added to the `DataController` which allows it to return itself wrapped in the read only class. 
Return a read only instance of the Controller on …
=> Return a Read Only Instance of the DataController on Player End State

BUILD.bazel, PlayerUI.podspec, generated.bzl, ios/plugins/ComputedPropertiesPlugin/Sources/ComputedPropertiesPlugin.swift, ios/plugins/ComputedPropertiesPlugin/Tests/ComputedPropertiesPluginTests.swift, plugins/computed-properties/core/BUILD, xcode/Podfile, xcode/Podfile.lock
- Wrap `ComputedPropertiesPlugin` for iOS
marked as `minor` since there was a wonky release 
=> iOS: Add swift wrapper for ComputedPropertiesPlugin

package.json, yarn.lock
Use slightly older version of the monaco editor in the storybook integration to make it easier to integrate the storybook plugin in plugins still using webpack4. 
Pin `@moncao-editor/react` to `4.3.1`
=> Pin @moncao-editor/react to non `.mjs` Only Version

scripts/release.sh
This doc deploy is blowing up with bazel errors and `--verbose_failures` did not provide additional insight. We just need to fix this prior to 1.0 but shouldnt block ourselves from moving forward right now just for having copies of major docs.
`latest` docs works fine
=> build: comment out major doc deploy for now

ios/packages/core/Sources/Types/Assets/BaseAssetRegistry.swift, ios/packages/core/Sources/Types/Assets/Wrappers.swift, ios/packages/swiftui/Sources/types/WrappedFunction.swift, ios/packages/swiftui/Sources/types/assets/WrappedAsset.swift, ios/packages/swiftui/Tests/SwiftUIRegistryTests.swift, ios/packages/swiftui/Tests/types/WrappedFunctionTests.swift
=> iOS: port async WrappedFunction update

tools/storybook/src/player/PlayerFlowSummary.tsx
Storybook error element has a `data-automation-id` property which allows it to be programmably found in tests
=> Add Automation ID to Error Element in Storybook

ios/packages/core/Sources/Types/Assets/Wrappers.swift, ios/packages/core/Sources/Types/Beacon.swift
Minor things missed when porting
- `Equatable` AssetBeacon
- public init for `MetaData`
=> iOS: make AssetBeacon equatable and add public init for metadata

PlayerUI.podspec
Fixed dependencies for iOS Reference Assets subspec, should have had as a dep, instead of relying on it as a peer dep
=> iOS: add SwiftUIPendingTransactionPlugin to reference asset dependencies

ios/packages/core/Sources/Types/Core/NavigationStates.swift, ios/packages/core/Tests/FlowStateTests.swift
The stacked attribute used in existing content is defined as Bool https://github.intuit.com/player-plugins/intuit/blob/next/plugins/view-attributes/react/src/index.tsx#L8
Change the objects value to take Any to support Bools as well
=> iOS - allow navigationFlowViewState attributes to take Any instead of string

.circleci/config.yml, ios/plugins/StageRevertDataPlugin/Tests/StageRevertDataPluginTests.swift
=> update iOS StageRevertDataPluginTests

ios/packages/core/Sources/Types/Core/Flow.swift, ios/packages/test-utils/ViewInspector/ui-test/AssetFlowViewTests.swift, ios/plugins/StageRevertDataPlugin/Tests/StageRevertDataPluginTests.swift, xcode/Podfile.lock
=> update iOS tests to transition inside afterTransition

docs/site/pages/plugins/swiftui-pending-transaction.mdx
The extra newline on this page causes it not to show up in the sidebar of the `Plugins` section and also causes the header elements to be improperly rendered.
=> Fix SwiftUIPendingTransactionPlugin Docs Page

jvm/BUILD, jvm/build.bzl, jvm/pom.tpl
Publish with minimal POM for OSS Sonatype requirements
=> [JVM] pom with minimal oss requirements

docs/site/next.config.mjs, docs/site/plugins/mdx-link-append-loader.js
Adds links to the documentation pages that open the github.dev web-based editor. The goal is to facilitate contributing to improving our docs.
Another solution would be point to the `.../edit/...` path, but github.dev, as an instance of VS Code running into the browser, seems to be a more ergonomic solution.
=> feat: add github.dev links to docs

docs/site/pages/plugins/beacon.mdx, docs/site/pages/plugins/check-path.mdx, docs/site/pages/plugins/common-expressions.mdx, docs/site/pages/plugins/common-types.mdx, docs/site/pages/plugins/computed-properties.mdx, docs/site/pages/plugins/console-logger.mdx, docs/site/pages/plugins/expression.mdx, docs/site/pages/plugins/external-action-view-modifier.mdx, docs/site/pages/plugins/external-action.mdx, docs/site/pages/plugins/metrics.mdx, docs/site/pages/plugins/partial-match-fingerprint.mdx, docs/site/pages/plugins/pub-sub.mdx, docs/site/pages/plugins/stage-revert-data.mdx, docs/site/pages/plugins/swiftui-pending-transaction.mdx, docs/site/pages/plugins/transition.mdx, docs/site/pages/plugins/types-provider.mdx
- Adds Cocoapods instructions for each plugin
- adds a usage example for each plugin
=> iOS: Update plugin documentation

docs/site/components/mdx-components.tsx, docs/site/pages/plugins/asset-provider.mdx
Added JSON section to the asset Provider
=> AssetProviderPlugin - Docs update

docs/site/plugins/mdx-link-append-loader.js
Use relative paths for the `Help to improve this page` doc's links, otherwise we get the absolute path pointing to the Bazel output.
=> fix: help to improve docs links with relative path

docs/site/plugins/mdx-link-append-loader.js
Add missing `.../docs/site/...` fragment to the help to improve docs' links.
=> fix: missing docs/site on docs links

BUILD.bazel
To fix publishing error for iOS
=> iOS: add asyncnodeplugin resource path to bazel.build zip

docs/site/components/mdx-components.tsx, docs/site/pages/assets/custom.mdx, docs/site/pages/assets/reference.mdx, docs/site/pages/getting-started.mdx
Organize common documentation to follow similar structure across platforms and use nested `PlatformTabs` to swap code blocks
<details>
<summary>📦 Published PR as canary version: <code>0.6.1--canary.287.9035</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.6.1--canary.287.9035
</details>
=> [Docs] Platform consolidation

android/demo/src/main/java/com/intuit/playerui/android/reference/demo/lifecycle/DemoPlayerViewModel.kt, android/player/src/main/java/com/intuit/playerui/android/asset/SuspendableAsset.kt, android/player/src/test/java/com/intuit/playerui/android/renderer/NestedAssetTest.kt, plugins/beacon/jvm/src/main/kotlin/com/intuit/playerui/plugins/beacon/BeaconPlugin.kt
Introduction of `AsyncHydrationTrackerPlugin` to provide a mechanism for reacting when `SuspendableAsset` hydration is completely finished.
```kotlin
androidPlayer.asyncHydrationTrackerPlugin!!.hooks.onHydrationComplete.tap(this::class.java.name) {
// process effects after hydration is complete
}
```
=> [Android] `AsyncHydrationTrackerPlugin`

core/player/src/expressions/evaluator.ts, core/player/src/expressions/parser.ts
While Player is strict about syntactically invalid expressions, it should still be allowed to execute them if the implementation desires. This change exposes the Expression Parser's `strict` attribute on the Expression Evaluator's hook to allow it to be set via the `resolveOptions` hook. This change also changes the behavior around throwing those errors to only throw recoverable errors if `strict` is `true`. 
Expose Expression Parser's strictness option via the `resolveOptions` hook
<details>
<summary>📦 Published PR as canary version: <code>0.7.2--canary.315.10130</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.7.2--canary.315.10130
</details>
=> Expression Parser Strictness

plugins/common-types/core/src/formats/__tests__/formats.test.ts, plugins/common-types/core/src/formats/index.ts
Common Types Plugin - Fix `commaNumber` Formatting when Using a Precision of 0
=> Fix `commaNumber` Formatting when Using a Precision of 0

.github/PULL_REQUEST_TEMPLATE.md
=> PR Checklist update

CONTRIBUTING.md, tools/build_ios_bundles.sh
- Updates the iOS contributing guide to call out node usage for precompile script
- Updates the `build_ios_bundles.sh` to do some additional setup to make precompile script more reliable from fresh clone
i tried rebasing #188 but something went very wrong
=> update iOS contributing guide

docs/site/pages/content/data-expressions.mdx, docs/site/pages/content/navigation.mdx
=> refactor nav docs slightly to better call out onEnd expressions

core/player/src/expressions/parser.ts, core/player/src/expressions/types.ts, core/player/src/expressions/utils.ts
Types - Expose types/utilities around expression parsing errors
=> Expose More Information About Expression Parsing Errors

docs/site/components/Navigation.tsx
Fixes:
- Version selector not properly redirecting
- Active page being reset when the version is changed
Docs - Fix version selector not working and preserve route when changing versions
=> Version Selector Fixes

ios/packages/core/Sources/Types/Core/BindingParser.swift, ios/packages/core/Sources/Types/Core/DataController.swift, ios/packages/core/Sources/Types/Hooks/DataControllerHooks.swift, ios/packages/core/Sources/Types/Hooks/Hook.swift, ios/packages/core/Tests/HeadlessPlayerTests.swift
expose on update hook so Swift plugins can recieve data changes
=> iOS: expose data controller onUpdate hook

docs/site/pages/dsl/index.mdx, docs/site/pages/dsl/schema.mdx, docs/site/pages/dsl/views.mdx
Updated some DSL related documentation
=> [Docs] DSL docs additions

CONTRIBUTING.md, android/demo/README.md
* Added Bazelisk to list of requirements in CONTRIBUTING.md to make first-time setup more hassle-free.
* Specified that no other Android SDK build tools should be installed aside from the one mentioned (otherwise there are build errors).
=> Add bazelisk to list of requirements; be more specific in Android build instructions

android/demo/src/main/java/com/intuit/playerui/android/reference/demo/ui/base/BasePlayerFragment.kt, android/player/src/main/java/com/intuit/playerui/android/extensions/Into.kt, android/player/src/main/java/com/intuit/playerui/android/ui/PlayerFragment.kt, scripts/mvn-install.sh
Currently,`playerViewModel.state` collection in `PlayerFragment` is a mix between UI updates and callback handling. This separates each to ensure the latest states take precedence for UI updates and such updates don't block the state callbacks.
<details>
<summary>📦 Published PR as canary version: <code>0.7.3--canary.343.11262</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.7.3--canary.343.11262
</details>
=> [Android] Reorganize `PlayerFragment` state updates

.npmrc, core/player/src/view/__tests__/view.test.ts, core/player/src/view/parser/index.ts, core/player/src/view/plugins/switch.ts
When multinodes contained switches; the switch would not evaluate correctly.
```
id: 'foo',
fields: [
staticSwitch: [
{
case: '{{foo.baz}}',
asset: {
id: 'input-1',
type: 'input',
},
},
{
case: '{{foo.bar}}',
asset: {
id: 'input-2',
type: 'input',
},
},
],
],
``` 
when staticSwitches get evaluated to false; the asset should not live in the AST, however there was a bug that caused staticSwitches not to get read as a switch when they were inside of multinodes.
=> Parse multi node switch fixv1

core/player/src/binding-grammar/__tests__/test-utils/ast-cases.ts, core/player/src/binding-grammar/custom/index.ts
Fix #157. Require two adjacent { for a binding.
=> Fix false positive binding with opening {

CONTRIBUTING.md
Moving away from npm and yarn. Switched docs to reflect pnpm and removed references to bazel build //... and bazel test //...
=> Update pnpm in contributing docs

android/player/src/main/java/com/intuit/playerui/android/AndroidPlayer.kt, docs/site/pages/getting-started.mdx, jvm/core/src/main/kotlin/com/intuit/playerui/core/bridge/runtime/PlayerRuntimeConfig.kt, jvm/j2v8/src/main/kotlin/com/intuit/playerui/j2v8/bridge/runtime/V8Runtime.kt, jvm/j2v8/src/main/kotlin/com/intuit/playerui/j2v8/extensions/Lock.kt
While trying to debug, the app would crash due to [this](https://github.com/player-ui/player/blob/main/jvm/j2v8/src/main/kotlin/com/intuit/playerui/j2v8/extensions/Lock.kt#L13) timeout. This PR moves the timeout to the `PlayerRuntimeConfig`.
NOTE: Happy to add some documentation around this. However, I cant find a suitable place in the docs site to add this. Please let me know whats the best place to add some documentation to.
=> [Android] Allowing timeout to be configured through PlayerRuntimeConfig

tools/addon-storybook/src/addons/events/index.tsx, tools/addon-storybook/src/dsl/transpile.ts
- undefined variable -> pull `darkMode` from hook, was probably lost in a rebase
- bump wasmURL version because it was getting a mismatch and erroring so Suspense never resolved
=> get storybook rendering again

plugins/reference-assets/swiftui/Sources/ReferenceAssetsPlugin.swift, plugins/reference-assets/swiftui/ViewInspector/SwiftUI/ActionAssetTests.swift, plugins/reference-assets/swiftui/ViewInspector/SwiftUI/CollectionAssetTests.swift, plugins/reference-assets/swiftui/ViewInspector/SwiftUI/InfoAssetTests.swift, plugins/reference-assets/swiftui/ViewInspector/SwiftUI/InputAssetTests.swift, plugins/reference-assets/swiftui/ViewInspector/SwiftUI/TextAssetTests.swift
Change `ReferenceAssetsPlugin` to check against registry type to register assets, instead of Player type. This allows asset registration to work with `SwiftUIAssetTestHelper` or `SwiftUIAssetUniTestCase` for the `getAsset` helper.
resolves #325 
=> iOS ReferenceAssetsPlugin: check registry type instead of player type

BUILD.bazel, MODULE.bazel
Reenable stamping for podspec with updated `stamp` rule
This should put iOS back in publishing parity with `main`
=> stamp podspec again with version

docs/storybook/src/reference-assets/Choice.mdx, docs/storybook/src/reference-assets/Choice.stories.tsx, package.json, plugins/reference-assets/components/src/index.test.tsx, plugins/reference-assets/components/src/index.tsx, plugins/reference-assets/core/BUILD, plugins/reference-assets/core/package.json, plugins/reference-assets/core/src/assets/choice/__tests__/transform.test.ts, plugins/reference-assets/core/src/assets/choice/index.ts, plugins/reference-assets/core/src/assets/choice/transform.ts, plugins/reference-assets/core/src/assets/choice/types.ts, plugins/reference-assets/core/src/assets/index.ts, plugins/reference-assets/core/src/plugin.ts, plugins/reference-assets/mocks/BUILD, plugins/reference-assets/mocks/choice/choice-basic.tsx, plugins/reference-assets/mocks/choice/choice-validation.tsx, plugins/reference-assets/react/src/__tests__/integration.test.tsx, plugins/reference-assets/react/src/assets/choice/Choice.tsx, plugins/reference-assets/react/src/assets/choice/hooks.tsx, plugins/reference-assets/react/src/assets/choice/index.ts, plugins/reference-assets/react/src/assets/index.tsx, plugins/reference-assets/react/src/components/ChoiceItem.tsx, plugins/reference-assets/react/src/plugin.tsx, pnpm-lock.yaml, tools/asset-testing-library/core/src/index.ts
- Added core support for the new reference asset - choice. (From https://github.com/player-ui/player/issues/181) "A choice asset represents a single selection choice, often displayed as radio buttons in a web context. This will allow users to test out more complex flows than just inputs + buttons."
- Extended `runTransform` to accept an `additionalPlugins` parameter to simplify testing for users of Player.
=> Choice Asset

plugins/async-node/core/src/index.test.ts, plugins/async-node/core/src/index.ts
=> Player 8901 - Fix typings for onAsyncNode hook

CONTRIBUTING.md
While trying to run OSS android, a few of us ran into an issue
`ModuleNotFoundError: No module named 'six.moves'`
This happens when your default python version is >= 3
=> Update CONTRIBUTING.md to include python dependency.

plugins/async-node/core/src/index.test.ts, plugins/async-node/core/src/index.ts
=> Ayncnode comments cleanup

core/player/src/__tests__/validation.test.ts, core/player/src/controllers/validation/binding-tracker.ts
Because the `afterNodeUpdate` tap from the resolver doesn't always pass the original parent of the node, the `addToTree` logic would fail to recreate the original tree structure of the nodes that were nested in multiple multi-nodes. This caused some bindings not to get tracked properly and allow the navigation controller to proceed even when there were blocking errors present. To fix this the following changes were made:
- During the `afterNodeUpdate` tap in `binding-tracker`, the `currentBindingTree` now uses the resolved nodes as the keys, and uses the `children` and `values` properties to get the child nodes instead of tracking it using the old `addToTree` function.
- In order to be compatible with the other taps and maps that still use the original node instead of the resolved one, …
=> Fix binding tracking for validations within nested multi-nodes

plugins/async-node/core/src/index.test.ts, plugins/async-node/core/src/index.ts
This PR fixes the Ability to resolve with nothing issue
=> This PR fixes the Ability to resolve with nothing issue

plugins/reference-assets/core/src/assets/info/types.ts, plugins/reference-assets/mocks/info/info-basic.tsx, plugins/reference-assets/mocks/info/info-dynamic-flow.tsx, plugins/reference-assets/mocks/info/info-modal-flow.tsx, plugins/reference-assets/react/src/assets/info/Info.tsx
Bazel 6 jvm add footer in info comp 
All tests passing in local
=> Bazel 6 jvm add footer in info comp

core/player/src/view/__tests__/view.test.ts
Static switch test  for false cases
=> working bazel test //core/player:player_eslint

plugins/reference-assets/android/src/androidTest/java/com/intuit/playerui/android/reference/assets/info/InfoTest.kt, plugins/reference-assets/android/src/main/java/com/intuit/playerui/android/reference/assets/info/Info.kt, plugins/reference-assets/android/src/main/res/layout/info.xml, plugins/reference-assets/components/src/index.test.tsx, plugins/reference-assets/mocks/info/info-modal-flow.tsx
Bazel 6 android base add footer to info reference asset
Please find test results:
All Tests passed in local : 
https://app.buildbuddy.io/invocation/aae39ed3-dde9-40ee-9518-af24a07eb123
=> This PR enables to add footer component to info reference asset in android

.circleci/config.yml
Ensure we build core native bundles before iOS so it can surely pull from the cache
=> apply strategy from pr builds to main & release builds

scripts/release.sh
Trying to debug why NPM is publishing to `latest` instead of `next`
=> Log debug info for npm next release

core/player/src/view/__tests__/view.test.ts, core/player/src/view/parser/utils.ts
Fixed switch parsing syntax issue for dynamic switches.
https://jira.intuit.com/browse/PLAYA-9067?filter=-1
=> Fixed switch parsing syntax issue for dynamic switches

.autorc, docs/site/components/App.tsx, docs/site/config/navigation.ts, docs/site/package.json, scripts/release.sh
- Fix next releases being tagged as latest on npm
- Fix doc site issues with github pages
- Fix missing dsl plugins page
=> Docs and Release Fixes

jvm/core/src/main/kotlin/com/intuit/playerui/core/bridge/hooks/NodeAsyncParallelBailHook1.kt, jvm/core/src/main/kotlin/com/intuit/playerui/core/bridge/hooks/NodeHook.kt, jvm/core/src/test/kotlin/com/intuit/playerui/core/bridge/PromiseTest.kt, jvm/dependencies/common.bzl, jvm/hermes/src/main/jni/JHermesRuntime.h, plugins/async-node/jvm/BUILD, plugins/async-node/jvm/api/async-node.api, plugins/async-node/jvm/deps.bzl, plugins/async-node/jvm/src/main/kotlin/com/intuit/playerui/plugins/asyncnode/AsyncNodePlugin.kt, plugins/async-node/jvm/src/test/kotlin/com/intuit/playerui/plugins/asyncnode/AsyncNodePluginTest.kt
This PR accommodates to this requirement https://github.com/player-ui/player/issues/459 i.e Port internal async node plugin implementation to android
Added a new component as per the following plugins/async-node
├── core
│   ├── BUILD
│   ├── src
│   └── package.json
└── jvm
├── BUILD
├── deps.bzl
├── src/main/kotlin/com/intuit/playerui/plugins/asyncnode
│   └── AsyncNodePlugin.kt
└── src/test/kotlin/com/intuit/playerui/plugins/asyncnode
└── AsyncNodePluginTest.kt
All tests are passing in local :
=> Async node android

scripts/release.sh
The latest `next` release on `main` failed to build the docs because it ran out of resources:
[![`//docs:gh_deploy` CI failure](https://github.com/user-attachments/assets/92e7bb18-897c-4d4b-a95b-25554306e559)](https://app.circleci.com/pipelines/github/player-ui/player/3173/workflows/86e56545-8827-4e8f-9683-2f1e6af008f0/jobs/16579)
This PR swaps `config=release` with `config=ci` because that flag contains the [resource constraints](https://github.com/player-ui/player/blob/28d0e47bc661d9c18cc64621c589d37c73ae6eee/.bazelrc#L50-L52) and also includes `--config=release`.
=> [CI] Swap release script to use `config=ci`

ios/core/Sources/Player/HeadlessPlayer.swift, ios/core/Sources/Types/Core/ConstantsController.swift, ios/core/Tests/HeadlessPlayerTests.swift, ios/swiftui/Sources/SwiftUIPlayer.swift
Issue: https://github.com/player-ui/player/issues/446
Test: 
1. add constants controller tests to playerUITests(unit tests)
2. Use reference-assets plugin TextAsset 
Simulator change(new value "abc" from constants):
TextAsset code change:
```
struct TextAssetView: View {
/// The viewModel with decoded data, supplied by `TextAsset`
@ObservedObject var model: AssetViewModel<TextData>
@Environment(\.constantsController) var constantsController: ConstantsController?
@ViewBuilder
var body: some View {
VStack {
if let link = model.data.modifiers?.first(where: { $0.type == "link" })?.metaData?.ref {
Text(model.data.value.stringValue ?? "").bold().modifier(LinkModifier(link)).accessibility(identifier: model.data.id)
} else {
let constantValue: String = constantsController?.getConstants(key: …
```
=> ios expose constantsController #446

android/player/src/main/java/com/intuit/playerui/android/AndroidPlayer.kt, jvm/core/src/main/kotlin/com/intuit/playerui/core/constants/ConstantsController.kt, jvm/core/src/main/kotlin/com/intuit/playerui/core/player/HeadlessPlayer.kt, jvm/core/src/main/kotlin/com/intuit/playerui/core/player/Player.kt, jvm/core/src/test/kotlin/com/intuit/playerui/core/player/HeadlessPlayerTest.kt
Android provide access to Player with [AssetContext](https://github.com/player-ui/player/blob/bfd6a11a8d6c7138daec4724a8f08e9d9c4b370b/android/player/src/main/java/com/intuit/playerui/android/AssetContext.kt#L19-L23)
Usage: 
assetContext.player.constantsController.getConstants()
<details>
<summary>📦 Published PR as canary version: <code>0.8.1--canary.489.16892</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.8.1--canary.489.16892
</details>
Expose the core Player [constantsController](https://github.com/player-ui/player/blob/9efce22c0cf315568213f7d2811b81096c1806df/core/player/src/player.ts#L91) to Android/JVM consumers
AndroidPlayer provides top-level api and plugins access including …
=> Android/JVM - expose constantController

.bazelrc, .circleci/config.yml, MODULE.bazel
fix for build error: 
```
BUILD.bazel:35:6: While resolving toolchains for target @fbjni//:host: No matching toolchains found for types 
@rules_foreign_cc~0.10.1//toolchains:ninja_toolchain.
To debug, rerun with --toolchain_resolution_debug='@rules_foreign_cc~0.10.1//toolchains:ninja_toolchain'
```
solution:
upgrade `rules_foreign_cc` to the latest version
https://github.com/bazelbuild/rules_foreign_cc/releases/tag/0.11.1 
=> fix:no matching toolchains:ninja_toolchain

.circleci/config.yml
Use custom bazelrc during next/release builds off of main branch closing #502
=> [skip ci] Update CircleCI Config to use Bazelrc During next/release Builds

ios/core/BUILD.bazel, ios/core/Tests/FlowStateTests.swift, ios/core/Tests/HeadlessPlayerTests.swift, ios/core/Tests/Types/Core/ExpressionEvaluatorTests.swift, ios/core/Tests/utilities/JSLoggerTests.swift, ios/core/Tests/utilities/JSValueExtensionsTests.swift, ios/swiftui/BUILD.bazel, ios/swiftui/Tests/ManagedPlayer/ManagedPlayerViewModelTests.swift, ios/test-utils-core/Sources/utilities/HeadlessPlayerImpl.swift, plugins/async-node/ios/BUILD.bazel, plugins/async-node/ios/Tests/AsynNodePluginTests.swift, plugins/check-path/ios/Tests/CheckPathPluginTests.swift, plugins/computed-properties/ios/Tests/ComputedPropertiesPluginTests.swift, plugins/console-logger/ios/Tests/PrintLoggerPluginTests.swift, plugins/external-action/ios/Tests/ExternalActionPluginTests.swift, plugins/pubsub/ios/Tests/PubSubPluginTests.swift, plugins/stage-revert-data/ios/Tests/StageRevertDataPluginTests.swift, tools/ios/util.bzl
Move HeadlessPlayerImpl PlayerUITestUtilitiesCore so it can be exposed and used by test helpers in FTR
<details>
<summary>📦 Published PR as canary version: <code>0.8.1--canary.500.17272</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.8.1--canary.500.17272
</details>
=> iOS: move HeadlessPlayerImpl from PlayerUIInternalTestUtilities to PlayerUITestUtilitiesCore

scripts/release.sh
NPM publish target changed when the js rules were updated but didn't get caught.
<details>
<summary>📦 Published PR as canary version: <code>0.9.1--canary.507.17377</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.9.1--canary.507.17377
</details>
=> Fix js Package Releases

core/player/src/view/resolver/index.ts, plugins/async-node/core/src/index.test.ts, plugins/async-node/ios/Tests/AsynNodePluginTests.swift, plugins/async-node/jvm/src/test/kotlin/com/intuit/playerui/plugins/asyncnode/AsyncNodePluginTest.kt
1. Revert flatten nested node change
2. update tests for all platforms
=> revert async node flatten

ios/core/Sources/Types/Assets/BaseAssetRegistry.swift, ios/core/Sources/Types/Generic/AnyType.swift, ios/core/Tests/Types/Generic/AnyTypeTests.swift
`AnyType` decoded as a part of the asset tree did not have `AnyTypeDecodingContext` to allow for `[String: Any]` decoding, that context is now added in `BaseRegistry` when decoding the asset tree
Including complex metadata for beacons would not reencode when passing the beacon from Swift to JSC in all scenarios. 
```json
{
"asset": {
"id": "action-1",
"type": "action",
"exp": "{{count}} = {{count}} + 1",
"label": {
"asset": {
"id": "action-label-1",
"type": "text",
"value": "Clicked {{count}} times"
}
},
"metaData": {
"beacon": {
"array": [{
"key": "value"
}],
"string": "value"
}
}
}
}
```
In this scenario, this metadata would be [decoded by the ActionAsset](https://github.com/player-ui/player/blob/main/plugins/reference-assets/swiftui/Sources/SwiftUI/ActionAsset.swift#L25), which …
=> iOS: Expand AnyType to handle deeply nested AnyType for beacon encoding

package.json, pnpm-lock.yaml
`leven` 4.0.0 is esm only and since we distribute esm and cjs we need to downgrade to a version of leven with cjs support
Fix CJS support for Reqct player
=> Fix CJS support for React Player

ios/core/Sources/Player/HeadlessPlayer.swift, ios/core/Tests/utilities/JSLoggerTests.swift, ios/logger/Sources/TapableLogger.swift, ios/logger/Tests/TapableLoggerTests.swift, ios/swiftui/Tests/SwiftUIRegistryTests.swift, plugins/console-logger/ios/Sources/PrintLoggerPlugin.swift, plugins/console-logger/ios/Tests/PrintLoggerPluginTests.swift
https://github.com/player-ui/player/issues/523
Prefixing message with the format `[Player] [\(logLevel)]:`  moved out of the Tapable logger and moved to PrintLoggerPlugin. Any consumers using their own LoggerPlugin will need to append the logLevel if they want to print it 
Before
```swift
public class CustomLoggingPlugin: NativePlugin {
public let pluginName = "CustomLoggingPlugin"
public func apply<P>(player: P) where P: HeadlessPlayer {
guard let player = player as? SwiftUIPlayer else { return }
player.logger.logLevel = .trace
player.logger.hooks.trace.tap(name: pluginName, { print("Custom message")\(($0))" ) })
...
}
```
After
```swift
public class CustomLoggingPlugin: NativePlugin {
public let pluginName = "CustomLoggingPlugin"
public …
```
=> ios: enhance tapable logger to handle variadic args from the JS log

docs/site/BUILD
=> Fix docs build visibility

docs/site/BUILD, docs/site/astro.config.mjs, docs/site/src/components/tools/VersionSelector.tsx, docs/site/src/content/docs/guides/getting-started.mdx, docs/site/src/content/docs/index.mdx, docs/site/src/content/docs/plugins/core/common-expressions.mdx, docs/site/src/content/docs/plugins/core/common-types.mdx, docs/site/src/content/docs/plugins/multiplatform/asset-provider.mdx, docs/site/src/content/docs/plugins/multiplatform/check-path.mdx, docs/site/src/content/docs/plugins/multiplatform/external-action.mdx, docs/site/src/content/docs/tools/storybook.mdx, docs/site/src/content/docs/xlr/usage.mdx, package.json, pnpm-lock.yaml
- Fix links for `latest` and `next` pages
- Add package manager tabs for js install instructions
- Fix version selector breaking on main page
=> More Doc Fixes

.circleci/config.yml
don't need to generate the HTML formatted coverage reports from genhtml, only the `_coverage_report.dat` is needed for codecov 
=> remove unneeded HTML report generation steps from build

ios/README.md
match the note style in the later part of the doc with newer markdown features in github, should make this section more clear
=> improve prominence of bazel build guidance for iOS targets

.github/PULL_REQUEST_TEMPLATE.md, docs/site/astro.config.mjs, docs/site/src/content/docs/authoring/index.mdx, docs/site/src/content/docs/authoring/plugins.mdx, docs/site/src/content/docs/authoring/schema.mdx, docs/site/src/content/docs/authoring/views.mdx
=> Add Missing DSL Docs

MODULE.bazel, jvm/hermes/deps.bzl, jvm/hermes/src/main/kotlin/com/intuit/playerui/hermes/bridge/runtime/HermesRuntime.kt, plugins/console-logger/jvm/BUILD.bazel, plugins/console-logger/jvm/deps.bzl, plugins/console-logger/jvm/src/main/kotlin/com/intuit/playerui/plugins/consolelogger/ConsoleLoggerPlugin.kt, plugins/console-logger/jvm/src/test/kotlin/com/intuit/playerui/plugins/consolelogger/ConsoleLoggerPluginTest.kt
This PR makes available a JVM ConsoleLoggerPlugin that can be added to any supported JS runtime in for the JVM, forwarding all console logs to a provided logger
<details>
<summary>📦 Published PR as canary version: <code>0.9.2--canary.552.18572</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.9.2--canary.552.18572
</details>
=> JVM ConsoleLoggerPlugin

ios/core/Sources/Player/HeadlessPlayer.swift
When reusing a `JSContext` that had already loaded JS classes, JavascriptCore would throw exceptions when walking through the dot separated classnames as JSValue can be non-nil with an underlying `undefined` value. Adding a check for `isUndefined` lets us short circuit the classname reference recursion and skip back to resource loading.
<details>
<summary>📦 Published PR as canary version: <code>0.10.2--canary.577.19320</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.10.2--canary.577.19320
</details>
=> iOS: JavascriptCore Exceptions when finding classes

docs/site/src/content/docs/plugins/multiplatform/shared-constants.mdx
The docs used the word "enable" that made us think that if a `dataPath` isnt provided, the constants will not be overridable through content. However, looking at the [code](https://github.com/player-ui/player/blob/7e2c1a691ea8e0aae1f2c412d145dcb4749d7164/plugins/shared-constants/core/src/index.ts#L45) thats not true.
Updated docs for Shared Constants Plugin to highlight the default dataPath used for overriding values
=> Update  to explicitly call out the default value for dataPath

jvm/core/src/main/kotlin/com/intuit/playerui/core/player/Player.kt, jvm/core/src/test/kotlin/com/intuit/playerui/core/player/PlayerHooksTest.kt
Expose onStart player hook for Android.
=> Expose onStart player hook for Android

plugins/common-expressions/core/src/expressions/index.ts, plugins/data-change-listener/core/BUILD, plugins/data-change-listener/core/package.json, plugins/data-change-listener/core/src/__tests__/index.test.ts, pnpm-lock.yaml
Fixed an issue in `common-exprssion-plugin` where the array update via concat didn't trigger the `data-change-listener`  and view update
<details>
<summary>📦 Published PR as canary version: <code>0.10.3--canary.572.19773</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.10.3--canary.572.19773
</details>
=> Data change listener fix

jvm/core/src/main/kotlin/com/intuit/playerui/core/bridge/hooks/NodeSyncHook.kt, plugins/metrics/jvm/src/main/kotlin/com/intuit/playerui/plugins/metrics/Metrics.kt, plugins/metrics/jvm/src/main/kotlin/com/intuit/playerui/plugins/metrics/MetricsPlugin.kt, plugins/metrics/jvm/src/test/kotlin/com/intuit/playerui/plugins/metrics/MetricsPluginTest.kt
Expose onFlowBegin, onFlowEnd, onRenderEnd metrics plugin hooks for Android
=> Expose metrics plugin hooks android

ios/demo/Sources/MockFlows.swift, plugins/async-node/ios/Tests/AsynNodePluginTests.swift, plugins/reference-assets/swiftui/UITests/ChatMessageAssetUITests.swift
core update can be found [here](https://github.com/player-ui/player/pull/575)
demo app screenshot:
doc update in core pr
Player streaming enhancement for iOS
Changes
- Update iOS PlayerUIDemo with Chat-message asset basic
- Update async-node-plugin and reference-assets-plugin tests
=> Async streaming iOS

ios/core/Sources/Types/Hooks/Hook.swift, plugins/metrics/swiftui/Sources/MetricsPlugin.swift, plugins/metrics/swiftui/ViewInspector/MetricsPluginTests.swift
Expose the following hooks for iOS Metrics plugin:
onRenderEnd
onFlowBegin
onFlowEnd
Add Hook3Decode to support onRenderEnd which recieves 3 parameters from the js hook
=> iOS: expose metrics plugin hooks

jvm/core/src/main/kotlin/com/intuit/playerui/core/flow/FlowInstance.kt, jvm/core/src/test/kotlin/com/intuit/playerui/core/flow/FlowControllerIntegrationTest.kt
Expose FlowInstance afterTransition hook for jvm
=> Expose FlowInstance afterTransition hook for jvm

jvm/core/src/main/kotlin/com/intuit/playerui/core/player/HeadlessPlayer.kt
Enable logs to identify main thread blocking operations, ensuring JS access in JVM is done exclusively off main thread
<details>
<summary>📦 Published PR as canary version: <code>0.10.5--canary.613.21050</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.10.5--canary.613.21050
</details>
=> enable blocking logs by default

WORKSPACE.bzlmod, android/player/src/main/java/com/intuit/playerui/android/ui/PlayerFragment.kt, jvm/hermes/src/main/kotlin/com/intuit/playerui/hermes/extensions/Lock.kt
`whenStarted` was automatically swapping to main dispatcher, this PR shifts the work to the dispatcher it was originally intended to run on
=> move renderIntoPlayerCanvas onto the correct thread

.bazelrc, .circleci/config.yml
Since passing secrets to forked builds is fully disabled, completely disable cache for those builds. 
=> Fully disable cache for forked builds

core/player/src/player.ts, docs/site/astro.config.mjs, react/player/src/player.tsx, tsup.config.ts
This reverts commit 6ed308100ab3dfe18d439335dc038bf68f8c1bc2, reversing changes made to 6fc1db4ebf87259073d72f33d675d0519823bae6.
<details>
<summary>📦 Published PR as canary version: <code>0.10.5--canary.648.22787</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.10.5--canary.648.22787
</details>
=> Revert "Merge pull request #646 from player-ui/ops/merge-636-and-637"

ios/core/Sources/Types/Generic/AnyType.swift, ios/core/Tests/Types/Generic/AnyTypeTests.swift
reopening because last one had unsigned commits
Should be able to return true when asserting two unknown data AnyTypes 
fix for getting XCTAssertEqual failed: ("unknownData") is not equal to ("unknownData")
=> iOS Anytype make unknowndata equatable

.circleci/config.yml, scripts/release.sh
<details>
<summary>📦 Published PR as canary version: <code>0.11.1--canary.650.22896</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.11.1--canary.650.22896
</details>
=> Prebuild Publishing Targets to Miinimize Chances of Releases Breaking

core/player/src/controllers/view/asset-transform.ts, core/player/src/controllers/view/controller.ts, core/player/src/controllers/view/index.ts, core/player/src/plugins/default-view-plugin.ts, core/player/src/view/plugins/asset-transform.ts, core/player/src/view/plugins/index.ts, plugins/asset-transform/core/src/__tests__/index.test.ts
Will close #667 
Move `AssetTransformCorePlugin` application after `applicability` and `switch` view plugins to ensure transforms properly apply to conditional assets.
<details>
<summary>📦 Published PR as canary version: <code>0.11.3--canary.668.23668</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.11.3--canary.668.23668
</details>
=> Fix transforms on assets with `applicability`

ios/swiftui/Sources/ManagedPlayer/ManagedPlayerViewModel.swift
Fix ManagedPlayerViewModel memory leak by adding weak self
=> fix iOS ManagedPlayerViewModel memory leak

core/player/src/view/builder/index.ts, core/player/src/view/resolver/__tests__/index.test.ts, plugins/async-node/core/src/__tests__/createAsyncTransform.test.ts, plugins/async-node/core/src/createAsyncTransform.ts, plugins/async-node/core/src/utils/__tests__/requiresAssetWrapper.test.ts, plugins/async-node/core/src/utils/index.ts, plugins/async-node/core/src/utils/requiresAssetWrapper.ts
- Update the `createAsyncTransform` util to consider different incoming node types coming from `getNestedAsset` option. Originally, this assumed that it would always be an `asset` node type and would asset-wrap the node, but to allow for some additional flexibility, the following rules are applied:
- Asset nodes and Applicability nodes with a value that is an asset node get asset wrapped like before.
- multi-nodes have their values spread into the initialized multi-node to keep the structure flat
- everything else gets added to the initialized multi-node as-is.
=> update createAsyncTransform to allow for different node types

docs/site/src/content/docs/plugins/multiplatform/async-node.mdx, plugins/async-node/core/src/__tests__/createAsyncTransform.test.ts, plugins/async-node/core/src/createAsyncTransform.ts
- Added `asyncNodePosition` as an option to `createAsyncTransform`. This lets user choose if the generated async node goes to the top or bottom of the generated multi-node.
=> add asyncNodePosition to createAsyncTransform options
