tools/cli/BUILD

Fixing the publish of the cli package

Add registry to cli pkg

---

WORKSPACE

Fix the dependency names for generated `package.json`

Bump rules_player. Fix package.json generation

---

.bazelrc
docs/site/BUILD
docs/site/pages/_app.tsx
package.json
yarn.lock

Analytics for docs

---

WORKSPACE
jvm/build.bzl
scripts/release.sh

configure JAR publishing to Maven Central via rules

---

.circleci/config.yml

import GPG key

---

jvm/build.bzl

fix maven repos

---

.bazelrc
.circleci/config.yml

Updates to test the results of remote caching on builds

Use remote caching for bazel targets

---

jvm/core/src/main/kotlin/com/intuit/player/jvm/core/asset/AssetWrapper.kt
jvm/core/src/main/kotlin/com/intuit/player/jvm/core/flow/FlowInstance.kt
jvm/core/src/test/kotlin/com/intuit/player/jvm/core/flow/FlowControllerIntegrationTest.kt
jvm/core/src/test/kotlin/com/intuit/player/jvm/core/serialization/NodeSerializationTest.kt
jvm/graaljs/src/main/kotlin/com/intuit/player/jvm/graaljs/bridge/runtime/GraalRuntime.kt
jvm/graaljs/src/main/kotlin/com/intuit/player/jvm/graaljs/bridge/serialization/encoding/GraalDecoders.kt
jvm/j2v8/src/main/kotlin/com/intuit/player/jvm/j2v8/bridge/serialization/encoding/V8Decoders.kt

bring over latest jvm code

---

.github/CODEOWNERS

Changing the match order to prioritize language specific folders over docs
See https://github.com/player-ui/player/pull/22#issuecomment-1192756117

Reorder docs match for CODEOWNERS

---

core/types/src/index.ts
core/view/src/parser/__tests__/__snapshots__/parser.test.ts.snap
core/view/src/parser/index.ts
core/view/src/parser/types.ts
core/view/src/plugins/__tests__/template.test.ts
core/view/src/plugins/template-plugin.ts
core/view/src/resolver/index.ts
core/view/src/resolver/types.ts
docs/site/pages/content/templates.mdx
language/dsl/BUILD
language/dsl/src/__tests__/schema.test.tsx
language/dsl/src/compiler/__tests__/compiler.test.tsx
language/dsl/src/compiler/compiler.ts
language/dsl/src/compiler/schema.ts
language/dsl/src/types.ts
plugins/asset-transform/core/src/__tests__/propertiesToSkip.test.ts
plugins/asset-transform/core/src/index.ts
plugins/asset-transform/core/src/propertiesToSkip.ts
plugins/beacon/react/BUILD
plugins/beacon/react/src/__tests__/index.test.tsx
plugins/check-path/core/src/index.test.ts
plugins/check-path/core/src/index.ts
plugins/check-path/react/BUILD
plugins/check-path/react/src/__tests__/check-path.test.tsx
tools/jest-coverage-mapper.js
tools/storybook/src/player/PlayerStory.tsx

Syncing with the latest changes

Sync updates

---

WORKSPACE

Should now properly push to CocoaPod trunk

update rules_player to 0.5.1

---

PlayerUI.podspec

guess i forgot to save this change initially

change version to placeholder for stamping

---

scripts/release.sh

rebuild the podspec, not the pod

---

scripts/release.sh

i thought it would use the cached podspec i just built the line before it

add release flag to run command

---

android/player/src/main/java/com/intuit/player/android/asset/RenderableAsset.kt
plugins/reference-assets/android/src/main/java/com/intuit/player/android/reference/assets/collection/Collection.kt
plugins/reference-assets/android/src/main/java/com/intuit/player/android/reference/assets/info/Info.kt
plugins/reference-assets/android/src/main/java/com/intuit/player/android/reference/assets/input/Input.kt

fix IR backend for kotlinx serialization

---

.circleci/config.yml

allow caching ios tests again

---

.autorc
scripts/after-release-pod-push.js

i dont think this is the reason for the failures, but i did include optional chaining in a JS file

fix pod release plugin

---

.autorc
scripts/after-shipit-pod-push.js

also defined owner/repo as i was using those properties in the pod plugin and they were undefined.. probably the reason for the 404

move pod push to afterShipIt to have upload-assets finish first

---

.circleci/config.yml
WORKSPACE

update `rules_player` to latest for building on Xcode 13.4.1

upgrade to xcode 13.4.1

---

.circleci/config.yml
.github/workflows/canary.yml

Will need to be merged before it is operational (workflow needs to exist on default branch before it can be used).

Canary workflow

---

.circleci/config.yml

Add GH to known hosts on release

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md

- Update PR template 
- Add extra comment for bug report template
- Update CONTRIBUTING to include more system info + iOS presetup / skip

update CONTRIBUTING doc with more system info, update templates

---

plugins/reference-assets/react/src/plugin.tsx

Export InfoAsset as XLR View

---

scripts/release.sh

Trying to fix release script which fails on full release publishing docs

remove version prefix from doc release path

---

docs/site/pages/content/dsl.mdx

Update the DSL documentation to fix imports and give an example of accessing the item value within a Template.

DSL documentation changes

---

docs/site/pages/assets/custom.mdx
docs/site/pages/getting-started.mdx
docs/site/pages/writing-plugins.mdx

Updated iOS `Writing Plugins` and fixed some wording in other guides

iOS: Update Writing Plugins guide

---

docs/site/components/PlayerTeam.tsx
docs/site/config/team.json

Minor Fixes for the Team page:
- Updates the Team page with the new members of the Player team. 
- Shuffles the order of the cards on every load.

Update Team Page with New Members

---

docs/site/pages/faqs.mdx

Minor Fixes for the FAQ page:
- Added links for getting started.
- Added links for storybook
- Added discord

docDays/updated FAQS

---

core/player/src/__tests__/view.test.ts
core/player/src/controllers/validation/controller.ts
core/player/src/controllers/view/controller.ts
plugins/common-expressions/core/src/expressions/index.ts
plugins/common-types/core/src/formats/utils.ts
plugins/data-change-listener/core/src/index.test.ts
plugins/data-change-listener/core/src/index.ts

- Skip view updates for silent data changes
- Replace `reduce` calls for performance reasons
- Fix data change events not cascading properly when setting data

[Sync] Performance and Bugfix

---

jvm/core/src/main/kotlin/com/intuit/playerui/core/player/HeadlessPlayer.kt
jvm/core/src/test/kotlin/com/intuit/playerui/core/player/HeadlessPlayerTest.kt

<details>
<summary>📦 Published PR as canary version: <code>0.7.1--canary.303.9547</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.7.1--canary.303.9547
</details>

[JVM] Handle invalid JSON as Player error

---

docs/site/pages/content/data-expressions.mdx

This is to address a documentation gap, these docs will need to have another pass taken for `ContentTabs` usage

add syntax examples for default expressions

---

docs/site/pages/dsl/schema.mdx

Docs - Update DSL Schema benefits section

[Docs] Update the DSL Benefits in Schema Section

---

.circleci/config.yml
CONTRIBUTING.md
plugins/async-node/core/src/index.test.ts
plugins/async-node/core/src/index.ts
plugins/async-node/core/src/types.ts
plugins/reference-assets/components/src/index.test.tsx
plugins/reference-assets/react/postcss.config.js
plugins/reference-assets/react/src/components/Separator.tsx

~~According to [codecov docs](https://docs.codecov.com/docs/merging-reports) you can just upload multiple reports in parallel and they will get merged.~~ Even with their [latest major](https://github.com/codecov/codecov-circleci-orb/releases/tag/v4.0.0) the circleci/codecov orb doesn't support `aarch64` so cant be run from an M1 executor
There is some [additional config](https://docs.codecov.com/docs/flags) that can be done to make the report a bit easier to read down the line, once this functionality is confirmed to work.
Also updated the requirements for the project to not require ruby, and bump the Xcode / Swift versions

Bazel-6: Upload Codecov reports

---

.bazelrc
.circleci/config.yml
.codecov.yml

adds a `--config=ci-mac` option to set the CPU/RAM limits for the macOS executor, as it has less memory than the docker executor

Specify some RC flags only for mac

---

CONTRIBUTING.md
docs/site/pages/assets/cross-platform.mdx
docs/site/pages/assets/transforms.mdx
newCONTRIBUTORS.md

Also fix a broken link in docs (#99)

Add Info on Commit Signing to Docs.

---

android/demo/README.md

Adding troubleshooting info for `Module not found: six.moves` error

---

ios/README.md

* add links in beginning to link to section
* add note about building all targets 

iOS Development guide: update readme

---

.circleci/config.yml

NPM registry moved from `.org` to `.com`

Fix NPM Registry URL

---

.circleci/config.yml

Specific Temurin Version

---

MODULE.bazel

Update to rules player 1.1.1

---

.circleci/config.yml

[skip ci] Fix Android Config Setup During Bazelrc Setup Phase During Build

---

jvm/hermes/src/main/jni/BUILD

Do not use android specific flags for `hermes_jni` host builds (testing purposes)

hermes_jni linkopt select

---

jvm/core/deps.bzl
jvm/core/src/main/kotlin/com/intuit/playerui/core/bridge/hooks/NodeAsyncWaterfallHook2.kt
jvm/core/src/test/kotlin/com/intuit/playerui/core/player/HeadlessPlayerTest.kt
plugins/beacon/jvm/src/main/kotlin/com/intuit/playerui/plugins/beacon/BeaconPlugin.kt
plugins/beacon/jvm/src/test/kotlin/com/intuit/playerui/plugins/beacon/BeaconPluginTest.kt

<details>
<summary>📦 Published PR as canary version: <code>0.9.2--canary.542.18680</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.9.2--canary.542.18680
</details>

Implemented cancelBeacon and buildBeacon hooks for Android

---

scripts/next-changelogs.js

Push up new changelog before continuing release process so new version is tagged to a commit that exists

Fix Releases

---

.bazelrc
.circleci/config.yml

Tests show the m2 medium executor performing about the same as the m1 large executor while costing less. 
Closes #551 
<!--
In an effort to standardize our process and code, please make sure you include documentation and/or update any existing documentation.
Please refer to our site https://player-ui.github.io/latest/about, and include any neccesary information that would be helpful to coders, developers, and learners.
If you are unable to update the current documents, please create an issue for us to get back to it.

Use m2 Medium executor

---

docs/site/src/content/docs/authoring/plugins.mdx

minor typo fixes in docs
updated the the authoring section in docs for DSL plugin

Updated Authoring content section in docs.mdx

---

CHANGELOG.md
scripts/next-changelogs.js

fix duplicate date in title for next changelogs

Fix Duplicate Date in Title for `next` Changelog Entries

---

jvm/core/src/main/kotlin/com/intuit/playerui/core/player/HeadlessPlayer.kt
jvm/j2v8/src/main/kotlin/com/intuit/playerui/j2v8/bridge/runtime/V8Runtime.kt

J2V8 Config from Consumer

---

docs/site/src/content/docs/authoring/index.mdx

Found a few broken links for Views and Schema authoring on the Overview page

Broken links fix for docs

---

ios/demo/BUILD.bazel
ios/demo/Sources/FlowManagerView.swift
ios/demo/Sources/PluginsAndPlayerCollection.swift
ios/demo/Sources/String+Extensions.swift
ios/internal-test-utils/Sources/FlowData.swift
ios/swiftui/Sources/ManagedPlayer/ManagedPlayer.swift
ios/swiftui/Sources/ManagedPlayer/ManagedPlayerViewModel.swift
ios/swiftui/ViewInspector/ManagedPlayer/ManagedPlayerTests.swift

<details>
<summary>📦 Published PR as canary version: <code>0.10.2--canary.570.19246</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.10.2--canary.570.19246
</details>

Support Smoother Experience When Loading a Viewless Flow on iOS

---

.circleci/config.yml
CHANGELOG.md
android/testutils/BUILD
android/testutils/deps.bzl
plugins/reference-assets/android/defs.bzl

<details>
<summary>📦 Published PR as canary version: <code>0.10.4--canary.602.20660</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.10.4--canary.602.20660
</details>

Execution Environment Resource Bump + Android TestUtils

---

.github/CODEOWNERS

Update CODEOWNERS File

---

.circleci/config.yml

Update Bazel Docker Image

---

.circleci/config.yml

remove runtime specification

---

.circleci/config.yml

This should fix PRs #636 and #637 

Use Readonly Key for Forked Builds

---

.circleci/config.yml

Fix name of forked bazelrc job

---

.circleci/config.yml
MODULE.bazel
jvm/defs.bzl
scripts/release.sh

<details>
<summary>📦 Published PR as canary version: <code>0.11.3--canary.662.23488</code></summary>
<br />
Try this version out locally by upgrading relevant packages to 0.11.3--canary.662.23488
</details>

Central Portal Migration

---

.circleci/config.yml

For some reason the original PR passed on the iOS stage but just failed on main. Reverting this change for now. 

Fix iOS Build Stage

---

core/player/src/player.ts

fix: import queueMicrotask

---

ios/README.md

Document a new caching issue affecting iOS builds and how to fix it.

Document common iOS Cache error and how to fix it

---

android/defs.bzl

Add pom template to android builds, required for releases to Maven Central.

Fix Android publishing
